sudo : required
services:
  - docker

before_install:
  - docker build -t wingrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wingrider/react-test npm test -- --coverage

after_success:
  - docker build -t wingrider/multi-client ./client
  - docker build -t wingrider/multi-nginx ./nginx
  - docker build -t wingrider/multi-server ./server
  - docker build -t wingrider/multi-worker ./worker

  #log in to docker hub
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

  #push to docker hub
  - docker push wingrider/multi-client
  - docker push wingrider/multi-nginx
  - docker push wingrider/multi-server
  - docker push wingrider/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-container"
  env: "MultiContainer-env"
  bucket_name: "elasticbeanstalk-us-east-2-676121265370"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
